#!/usr/bin/env python3

import os

# TODO: pick random from

# notes
os.system('open /Users/zach/Desktop/zvmac/notes/za/passions/viz/viz.md')

# progress
os.system('open /Users/zach/Desktop/zvmac/materials/za/passions/viz/#日志')
