#!/usr/bin/env bash

open "$HOME/Desktop/zvmac/materials/za/passions/dance"
open "$HOME/Desktop/zvmac/notes/za/passions/dance/floor.md"
open "$HOME/Desktop/zvmac/notes/za/passions/dance/salsa.md"
/Applications/VLC.app/Contents/MacOS/VLC -Z "$HOME/Desktop/zvmac/materials/za/passions/dance/floor/input"
