#!/usr/bin/env python3

import os

# blog
os.chdir('/Users/zach/Desktop/zvmac/materials/sw/network/4-app-layer/personal-site/zach-valenta/notes')
os.system('open 2014-lewis-flash-boys.md')

# finance notes
os.chdir('/Users/zach/Desktop/zvmac/notes/za/non-fiction/business')
os.system('open finance-corporate.md')

# pdf
os.chdir('/Users/zach/Desktop/zvmac/materials/za/non-fiction/business/finance/flash-boys')
os.system('open flash-boys.pdf')

# dir
os.chdir('/Users/zach/Desktop/zvmac/materials/za/non-fiction/business/finance')
os.system('open flash-boys')
