#!/usr/bin/env python3

from random import randint, sample

# for chord, quality in zip(sample([1, 2, 3, 4, 5, 6, 7], 4), sample(["°", "-", "M", "+", ], 4)):
#     print(chord, quality)

print("\n🥁 https://www.rhythmrandomizer.com \n")

print("\n🎼 CHORDS\n")
for chord in sample(["I", "ii", "iii", "IV", "V", "vi", "vii°"], randint(2, 4)):
    print(chord)

print("\n🎶 MELODY\n")
for melody in sample([1, 3, 4, 5, 7], randint(2, 5)):
    print(melody)
print("\n")
