#!/usr/bin/env python3

from random import randint, sample

# for chord, quality in zip(sample([1, 2, 3, 4, 5, 6, 7], 4), sample(["°", "-", "M", "+", ], 4)):
#     print(chord, quality)

for chord in sample(["I", "ii", "iii", "IV", "V", "vi", "vii°"], randint(2, 4)):
    print(chord)
