#!/usr/bin/env bash

cd "$HOME/Desktop/zvmac/notes" || exit
echo -en "\n"

# RM / MV
mvrm="$(git ls-files --deleted)"
mvrm_bg="orangered"
mvrm_fg="$(pastel textcolor "$mvrm_bg")"
if [ -n "$mvrm" ]; then
    pastel paint "$mvrm_fg" --on "$mvrm_bg" " moved / removed "
    echo -en "\n${mvrm}\n\n"
fi

# ADDED
added="$(git ls-files --others --exclude-standard)"
added_bg="lawngreen"
added_fg="$(pastel textcolor "$added_bg")"
if [ -n "$added" ]; then
    pastel paint "$added_fg" --on "$added_bg" " added "
    echo -en "\n${added}\n\n"
fi

# WORKING TREE
updated="$(git diff --stat-width=75 | sort -k 3 | sed \$d)"
update_bg="peru"
update_fg="$(pastel textcolor "$update_bg")"
if [ -n "$updated" ]; then
    pastel paint "$update_fg" --on "$update_bg" " working tree "
    echo -en "\n${updated}\n"
    echo -en "\n"
    total_files_touched="$(git s | wc -l)"
    echo "total files touched: ${total_files_touched}"
    time_since_last_commit="$(git rev-parse HEAD | git show -s --format=%cr)"
    echo -en "time since last commit:    ${time_since_last_commit}\n\n"
fi

# SPRINT
sprint_bg="steelblue"
sprint_fg="$(pastel textcolor "$sprint_bg")"
pastel paint "$sprint_fg" --on "$sprint_bg" " sprint "
echo -en "\n"
sprint_commits="$(git log master..sprint --oneline)"
echo -en "${sprint_commits}\n\n"


# MASTER
master_bg="pink"
master_fg="$(pastel textcolor "$master_bg")"
pastel paint "$master_fg" --on "$master_bg" " master "
echo -en "\n"
recent_commits="$(git log master -n 3 --oneline --decorate)"
echo -en "${recent_commits}\n\n"
