#!/usr/bin/env bash

# TODO: time since last commit

cd "$HOME/Desktop/zvmac/notes"
git s
echo -en "\n"

files_touched="$(git s | wc -l)"
echo "files touched: ${files_touched}"

time_since_last_commit="$(git rev-parse HEAD | git show -s --format=%cr)"
echo "time since last commit: ${time_since_last_commit}"
