#!/usr/bin/env bash

echo -en "\n"
grep --color=auto -A 9 schedule "$HOME/Desktop/zvmac/notes/jay/za/process.md" | bat -l markdown
grep --color=auto -A 6 week "$HOME/Desktop/zvmac/notes/jay/za/reminders.md" | bat -l markdown
