#!/usr/bin/env python3

"""
another alternative to rm
bc other options are npm based https://github.com/sindresorhus/trash
"""

import sys
from send2trash import send2trash

for i in sys.argv[1:]:
	try:
		send2trash(i)
	except OSError:
		print('❓  could not find file/dir to delete')
