#!/usr/bin/env python3

"""
qiu = wrapper around httpie

httpie version: 0.9.9
"""

import argparse
import os
import sys


def parse_args():
	parser = argparse.ArgumentParser(
		description='📡 wrapper around httpie',
		usage='📝 qiu -j payload.json -m POST -po 5000 -pa api/foo/',
	)
	parser.add_argument("-j", "--json", help=".json for request", action='store')
	parser.add_argument("-m", "--method", help="HTTP method", action='store')
	parser.add_argument("-pa", "--path", help="path", action='store')
	parser.add_argument("-po", "--port", help="port number", type=int, nargs='?', default=None)
	if len(sys.argv) == 1:
		parser.print_help()
		sys.exit()
	return parser.parse_args()


# take args
args = parse_args()

# base URL
command = 'http://127.0.0.1:{}'.format(args.port)

# path
if args.path:
	command = '{}/{}'.format(command, args.path)

# payload
if args.json:
	command = '{} @{}'.format(command, args.json)

# method
if args.method:
	command = '{} {}'.format(args.method, command)

# add command
command = 'http {}'.format(command)

# make req
os.system(command)
