#!/usr/bin/env bash

charm $HOME/Desktop/zvmac/materials/sw/za/algos/impl
open $HOME/Desktop/zvmac/materials/sw/za/algos/grokking/grokking-algos.pdf
open $HOME/Desktop/zvmac/notes/sw/za/za/algos.md
open $HOME/Desktop/zvmac/notes/sw/lang/python/python.md
