#!/usr/bin/env python3

import os
import random

# open random pic
os.chdir('/Users/zach/Desktop/zvmac/materials/za/passions/viz/lessons')
pics = [x for x in os.listdir('.') if x[-3:] in ('jpg', 'png')]
pic_to_open = random.choice(pics)
os.system('open {}'.format(pic_to_open))

# open note
os.system('open /Users/zach/Desktop/zvmac/notes/za/passions/viz/viz.md')
os.system('/Users/zach/Desktop/zvmac/materials/za/passions/viz/lessons')
