#!/usr/bin/env bash

# TODO: pick random from `accompaniment`

open "$HOME/Desktop/zvmac/notes/za/passions/viz/viz.md"
open "$HOME/Desktop/zvmac/materials/za/passions/viz/output/sketchnote"
open "$HOME/Desktop/zvmac/materials/za/passions/viz/input/emiliano-ponzi-cars.jpg"
